version: '3.8'
services:
  jaeger:
    network_mode: "bridge"
    image: jaegertracing/all-in-one:1.8 
    # XXX uncomment if you need to debug your jaeger setup
    command: --memory.max-traces 10000
    ports:
      - 16686:16686
  postgres:
    network_mode: "bridge"
    image: postgres:11
    environment:
      - "POSTGRES_USER=tinyci"
      - "POSTGRES_PASSWORD=tinyci"
      - "POSTGRES_DB=tinyci"
    volumes:
      - "./.db:/var/lib/postgresql/data"
  react:
    network_mode: "bridge"
    image: tinyci/ui:latest
    command: caddy run -config /Caddyfile
    ports:
      - 3000:3000
  hooksvc:
    network_mode: "bridge"
    image: tinyci/release:main
    command: tinyci -c /hooksvc.yaml service hooksvc
    volumes:
      - "./hooksvc.yaml:/hooksvc.yaml"
    links:
      - tinyci
    depends_on:
      - tinyci
  tinyci:
    network_mode: "bridge"
    image: tinyci/release:main
    command: tinyci -c /services.yaml launch
    environment:
      - "JAEGER_AGENT_HOST=jaeger"
      - "USE_JAEGER=1"
      - "DEBUG=1"
      - "GIN_MODE=release"
    volumes:
      - "./services.yaml:/services.yaml"
      - "./.logs:/var/tinyci/logs"
    links:
      - jaeger
      - postgres
    depends_on:
      - postgres
  migrator:
    network_mode: "bridge"
    image: tinyci/release:main
    command: migrator -t postgres -u tinyci -d tinyci -p tinyci /usr/local/bin/migrations/tinyci
    links:
      - postgres
    depends_on:
      - postgres
  httpmux:
    network_mode: "bridge"
    image: caddy:2.3.0
    command: caddy run -config /Caddyfile
    ports:
      - 443:443
    volumes:
      - "./Caddyfile:/Caddyfile"
    links:
      - react
      - tinyci
      - hooksvc
    depends_on:
      - react
      - tinyci
      - hooksvc
  runner:
    network_mode: "bridge"
    privileged: true
    image: tinyci/runners:latest
    command: "/usr/local/bin/overlay-runner -c /runner.yaml"
    volumes:
      - "./runner.yaml:/runner.yaml"
      - "./.runner:/var/db/git:shared,rw"
      - "./.runner-overlay:/var/db/overlay:shared,rw"
    links:
      - tinyci
    depends_on:
      - tinyci
